"""create sentiments table

Revision ID: 395b5bbb01f6
Revises: 140f867b1df3
Create Date: 2026-07-22 12:31:38.031854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395b5bbb01f6'
down_revision: Union[str, None] = '140f867b1df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], name=op.f('fk_sentiments_journal_id_journal_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentiments'))
    )
    with op.batch_alter_table('sentiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiments_journal_id'), ['journal_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiments_journal_id'))

    op.drop_table('sentiments')
    # ### end Alembic commands ###
