"""create weekly_summaries table

Revision ID: 7f3b24d6c2bb
Revises: 395b5bbb01f6
Create Date: 2026-07-22 13:51:45.853908
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3b24d6c2bb'
down_revision: Union[str, None] = '395b5bbb01f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_summaries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_summaries')),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_summaries_user_id_week_start')
    )
    with op.batch_alter_table('weekly_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_summaries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_summaries_user_id'))

    op.drop_table('weekly_summaries')
    # ### end Alembic commands ###
